# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Extensions to default config
homeassistant:
  customize: !include customizations.yaml
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# Enable python scripting
python_script:

# Includes for integrations
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
logbook: !include logbook.yaml
mqtt: !include mqtt.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
rest: !include rest.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
utility_meter: !include utility_meters.yaml

# Custom Log Levels
logger:
  default: warning
  logs:
    custom_components.openevse: error
    custom_components.bedjet.pybedjet: error
    custom_components.simple_plant: error
    homeassistant.components.apple_tv: fatal
    homeassistant.components.automation.climate_workshop_hvac: error
    homeassistant.components.matter: error
    homeassistant.components.openevse: error
    homeassistant.components.python_script: warning
    homeassistant.components.sensor.recorder: error
    homeassistant.components.yamaha_musiccast.coordinator: fatal
    roborock.data.code_mappings: error
    zigpy.application: error